global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert.rules"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

scrape_configs:
  - job_name: '5g-core'
    static_configs:
      - targets: ['amf-service:8000', 'smf-service:8001', 'upf-service:8002']

  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node

